# Generated by Django 4.1.4 on 2022-12-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_product_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="slideshow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_season",
                    models.CharField(
                        choices=[
                            ("SPRING", "Spring"),
                            ("SUMMER", "Summer"),
                            ("AUTUMN", "Autumn"),
                            ("WINTER", "Winter"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image_file", models.ImageField(upload_to="static/media/slideshow")),
            ],
        ),
    ]
