# Generated by Django 4.1.4 on 2022-12-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_slideshow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(upload_to="static/media/products"),
        ),
    ]
