# Generated by Django 4.1.4 on 2022-12-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_brand_alter_product_product_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.type"
            ),
        ),
    ]
