# Generated by Django 4.1.4 on 2022-12-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_type_alter_product_product_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brand",
            old_name="brande_image",
            new_name="brand_image",
        ),
    ]
