# Generated by Django 4.1.4 on 2023-01-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_shipping"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=100)),
                ("comment", models.TextField(max_length=1000)),
            ],
        ),
    ]
